# Generated by Django 2.1.7 on 2019-03-27 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='iwansell@gmail.com', max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('display_pic', models.FileField(default='anon.png', upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(default='Federal University of Technology Minna', max_length=100)),
                ('campus_code', models.CharField(default='FUTminna', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClientRateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='EHaggler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_2', models.IntegerField()),
                ('delete_for_1', models.BooleanField(default=False)),
                ('delete_for_2', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='EShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('catch_board', models.FileField(upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='EShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EShop')),
            ],
            options={
                'ordering': ['subcategory'],
            },
        ),
        migrations.CreateModel(
            name='EShopRateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EShop')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteEShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('eshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EShop')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('feed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reset_code', models.CharField(default='123579', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ehaggler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EHaggler')),
                ('messenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.FileField(default='product.png', upload_to='')),
                ('starting_price', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='RecentView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(default='product.png', upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(default='product.png', upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Category')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Product'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Product'),
        ),
        migrations.AddField(
            model_name='eshopratereview',
            name='ratereview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.RateReview'),
        ),
        migrations.AddField(
            model_name='eshopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Product'),
        ),
        migrations.AddField(
            model_name='eshopproduct',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.SubCategory'),
        ),
        migrations.AddField(
            model_name='clientratereview',
            name='ratereview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.RateReview'),
        ),
        migrations.AddField(
            model_name='account',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus'),
        ),
    ]
