# Generated by Django 2.1.7 on 2019-06-03 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientratereview',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='eshopratereview',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='clientratereview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eshopratereview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
