# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='EShopRateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EShop')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RateReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='productfavoriter',
            name='account',
        ),
        migrations.RemoveField(
            model_name='productfavoriter',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductFavoriter',
        ),
        migrations.AddField(
            model_name='eshopratereview',
            name='ratereview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.RateReview'),
        ),
        migrations.AddField(
            model_name='clientratereview',
            name='ratereview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.RateReview'),
        ),
    ]
