# Generated by Django 2.1.7 on 2019-06-24 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0002_auto_20190603_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('winners', models.IntegerField()),
                ('prizes', models.TextField()),
                ('terms_conditions', models.TextField()),
                ('about_organizer', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('tweet_id', models.CharField(max_length=100)),
                ('tweet', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Traffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet_id', models.IntegerField(default=11)),
                ('ticket_no', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raffle_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.RaffleBook')),
            ],
        ),
        migrations.CreateModel(
            name='TraffleClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('dp', models.CharField(default='null', max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raffle_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.RaffleBook')),
                ('traffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Traffle')),
            ],
        ),
        migrations.AddField(
            model_name='traffle',
            name='traffle_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.TraffleClient'),
        ),
        migrations.AddField(
            model_name='rafflebook',
            name='traffle_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.TraffleClient'),
        ),
    ]
