# Generated by Django 2.1.7 on 2019-03-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0002_auto_20190327_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(default='anon.png', upload_to=''),
        ),
    ]
