# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0003_auto_20180605_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('eshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EShop')),
            ],
        ),
    ]
