# Generated by Django 2.1.7 on 2019-03-30 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0003_auto_20190328_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='EShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Category')),
            ],
        ),
        migrations.AddField(
            model_name='eshop',
            name='about',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='eshop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eshopcategory',
            name='eshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.EShop'),
        ),
    ]
