# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-17 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0005_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='gurls_clothing', max_length=50),
        ),
    ]
