# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0006_category_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='08109599597', max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_name',
            field=models.CharField(max_length=50),
        ),
    ]
