# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-19 19:31
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0007_auto_20180619_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messenger',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
