# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-21 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0010_auto_20180621_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eshopproduct',
            options={'ordering': ['subcategory']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
    ]
