# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-28 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0011_auto_20180621_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='reset_password',
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='reset_code',
            field=models.CharField(default='123579', max_length=30),
        ),
    ]
