# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-29 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0012_auto_20180628_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus'),
        ),
    ]
