# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-29 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0013_product_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshop',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus'),
        ),
        migrations.AddField(
            model_name='sponsored',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus'),
        ),
        migrations.AddField(
            model_name='trending',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus'),
        ),
    ]
