# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0014_auto_20180629_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eshop',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
