# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0015_auto_20180704_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
